SELECT (SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith') AS fightsCount, 
(SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith' AND status = 0) AS losses, 
(SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith' AND status = 1) AS wins, 
(SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith' AND status = 2) AS currentlyPlaying,
(SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith' AND status = 3) AS forfeits,
(SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith' AND status = 4) AS fightsPendingReady,
(SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith' AND status = 5) AS fightsPendingStart,
(SELECT Count(idFight) FROM nsfw_activefighters WHERE idFighter = 'Aelith' AND status = 5) AS fightsPendingDraw,
(SELECT assignedTeam FROM nsfw_activefighters WHERE idFighter = 'Aelith' group by assignedTeam ORDER BY Count(*) DESC LIMIT 1) AS favoriteTeam,
IFNULL((SELECT AVG(diceScore) FROM nsfw_actions WHERE idAttacker = 'Aelith'),0) AS averageDiceRoll,
(SELECT Count(missed) FROM nsfw_actions WHERE idAttacker = 'Aelith') AS missedAttacks,
(SELECT Count(*) FROM nsfw_actions WHERE idAttacker = 'Aelith') AS actionsCount,
(SELECT Count(*) FROM nsfw_actions WHERE idDefender = 'Aelith') AS actionsDefended,
(SELECT Count(*) FROM nsfw_actions WHERE type = 0 AND (idAttacker = 'Aelith') AND missed = false) AS brawlAtksCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 1 AND missed = false AND (idAttacker = 'Aelith')) AS sexstrikesCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 2 AND missed = false AND (idAttacker = 'Aelith' OR idDefender = 'Aelith')) AS tagsCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 3 AND missed = false AND idAttacker = 'Aelith') AS restCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 4 AND missed = false AND idAttacker = 'Aelith') AS subholdCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 5 AND missed = false AND idAttacker = 'Aelith') AS sexholdCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 6 AND missed = false AND idAttacker = 'Aelith') AS bondageCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 7 AND missed = false AND idAttacker = 'Aelith') AS humholdCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 8 AND missed = false AND idAttacker = 'Aelith') AS itemPickups,
(SELECT Count(*) FROM nsfw_actions WHERE type = 9 AND missed = false AND idAttacker = 'Aelith') AS sextoyPickups,
(SELECT Count(*) FROM nsfw_actions WHERE type = 10 AND missed = false AND idAttacker = 'Aelith') AS degradationCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 11 AND missed = false AND idAttacker = 'Aelith') AS forcedWorshipCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 12 AND missed = false AND idAttacker = 'Aelith') AS highriskCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 13 AND missed = false AND idAttacker = 'Aelith') AS penetrationCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 14 AND missed = false AND idAttacker = 'Aelith') AS stunCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 15 AND missed = false AND idAttacker = 'Aelith') AS escapeCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 16 AND missed = false AND idAttacker = 'Aelith') AS submitCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 17 AND missed = false AND idAttacker = 'Aelith') AS straptoyCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 18 AND missed = false AND idAttacker = 'Aelith') AS finishCount,
(SELECT Count(*) FROM nsfw_actions WHERE type = 19 AND missed = false AND idAttacker = 'Aelith') AS masturbateCount